"""Add task_dependencies table for high-performance dependency resolution

Revision ID: 3d13447b7f13
Revises: 5bec681e9760
Create Date: 2025-06-27 17:09:12.308316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3d13447b7f13"
down_revision: Union[str, None] = "5bec681e9760"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_dependencies",
        sa.Column("dag_id", sa.String(length=250), nullable=False),
        sa.Column("task_id", sa.String(length=250), nullable=False),
        sa.Column("upstream_task_id", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("dag_id", "task_id", "upstream_task_id"),
    )
    op.create_index(
        "idx_task_deps_downstream",
        "task_dependencies",
        ["dag_id", "upstream_task_id"],
        unique=False,
    )
    op.create_index(
        "idx_task_deps_upstream",
        "task_dependencies",
        ["dag_id", "task_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_task_deps_upstream", table_name="task_dependencies")
    op.drop_index("idx_task_deps_downstream", table_name="task_dependencies")
    op.drop_table("task_dependencies")
    # ### end Alembic commands ###
