"""Initial migration

Revision ID: 5bec681e9760
Revises:
Create Date: 2025-06-14 08:45:09.115387

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5bec681e9760"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dag_id", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("schedule_interval", sa.String(length=100), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.String(length=5), nullable=True),
        sa.Column("last_parsed_time", sa.DateTime(), nullable=True),
        sa.Column("last_scheduler_run", sa.DateTime(), nullable=True),
        sa.Column("fileloc", sa.String(length=2000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dag_dag_id"), "dag", ["dag_id"], unique=True)
    op.create_table(
        "dag_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dag_id", sa.String(length=255), nullable=False),
        sa.Column("run_id", sa.String(length=255), nullable=False),
        sa.Column("execution_date", sa.DateTime(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=True),
        sa.Column("run_type", sa.String(length=50), nullable=True),
        sa.Column("external_trigger", sa.String(length=5), nullable=True),
        sa.ForeignKeyConstraint(["dag_id"], ["dag.dag_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "dag_id", "execution_date", name="uq_dag_run_dag_id_execution_date"
        ),
        sa.UniqueConstraint("dag_id", "run_id", name="uq_dag_run_dag_id_run_id"),
    )
    op.create_index(op.f("ix_dag_run_dag_id"), "dag_run", ["dag_id"], unique=False)
    op.create_index(
        op.f("ix_dag_run_execution_date"), "dag_run", ["execution_date"], unique=False
    )
    op.create_index(op.f("ix_dag_run_run_id"), "dag_run", ["run_id"], unique=False)
    op.create_index(op.f("ix_dag_run_state"), "dag_run", ["state"], unique=False)
    op.create_table(
        "task_instance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=False),
        sa.Column("dag_run_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("queued_at", sa.DateTime(), nullable=True),
        sa.Column("log_filepath", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(["dag_run_id"], ["dag_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "task_id", "dag_run_id", name="uq_task_instance_task_id_dag_run_id"
        ),
    )
    op.create_index(
        op.f("ix_task_instance_state"), "task_instance", ["state"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_instance_state"), table_name="task_instance")
    op.drop_table("task_instance")
    op.drop_index(op.f("ix_dag_run_state"), table_name="dag_run")
    op.drop_index(op.f("ix_dag_run_run_id"), table_name="dag_run")
    op.drop_index(op.f("ix_dag_run_execution_date"), table_name="dag_run")
    op.drop_index(op.f("ix_dag_run_dag_id"), table_name="dag_run")
    op.drop_table("dag_run")
    op.drop_index(op.f("ix_dag_dag_id"), table_name="dag")
    op.drop_table("dag")
    # ### end Alembic commands ###
